# Uncomment the next line to define a global platform for your project
# platform :tvos, '14.0'

target 'MobileUserConsent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileUserConsent
	pod 'OneTrust-CMP-tvOS-XCFramework'
	pod 'OneTrust-CMP-XCFramework'

  target 'MobileUserConsentTests' do
    # Pods for testing
  end

end
