# Uncomment the next line to define a global platform for your project
# platform :tvos, '11.0'

target 'MobileUserConsent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
# Pods for OTPublishersNativeAppTvOS-Pods sample app.
  pod 'OneTrust-CMP-tvOS-XCFramework', '~> 6.36.0.0'

  # Pods for MobileUserConsent

  target 'MobileUserConsentTests' do
    # Pods for testing
  end

end
